name: SimonSay
version: 1
api:
 - 3.0.6
 - 3.0.0
 - 4.0.0
author:
 - tungsten
description: SimonSay Plugin
main: tungsten_simonsay\Loader

#commands:
# ss:
#  description: "Simon Say Command"
#  command: /ss
#  permission: simset.tungsten
#  default: OP
  