
#dont change line 2
sign:
   line1: "§e-§6=§eSimonSay§6=§e-"
   line2: "§b{game}"
   line3: "§c{count}§f/§a{max}"
   line4: "{status}"
   
#Can change safely
status:
   waiting: "§eWaiting"
   running: "§aRunning"
#commands ran when player wins

winning_commands:
   - say [HungerGames] %player% won the match %game%!

#wait_time is countdown time
#timeToPlayAGame is time to play each game in simonsay
#wait_time_pergame is wait time between two game in simonsay   
ss_games:
  test:
    min_players: 1
    max_players: 8
    wait_time: 10
    timeToPlayAGame: 20
    wait_time_pergame: 5
    lobby_pos:
      x: 4
      y: 127
      z: 93
      level: world
...
