SimSiMi:
   simmaytuoiroi : §f[§eSimSiMi§f] -> Sim nam nay 10 tuoi  
   simthichgi : §f[§eSimSiMi§f] -> Sim thich nuoi meo
   simlatraihaygai : §f[§eSimSiMi§f] -> Sim la gai nha
   simoi : §f[§eSimSiMi§f] -> Sim day
   